modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="unnamed_minecraft_mod"
version="1.0.0"
displayName="Unnamed Minecraft Mod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Starlii10"

[[dependencies.unnamed_minecraft_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




